import { Timestamp } from "@firebase/firestore";



/**
 * interface of a message in chat
 *
 * @export
 * @interface Message
 */
export interface Message {
    /** text of the message */
    text: string,
    /** user id of the sender */
    senderUID: string,
    /** timestamp of the created message generated by firebase */
    timestamp: Timestamp,
    /** relationship */
    sendingRelationship: string[],
}



/**
 * interface of a chat
 *
 * @export
 * @interface Chat
 */
export interface Chat {
    /** id of the chat */
    uid: string,
    /** user the chat is directed to */
    recipientUser: string,
    /** text of last message */
    lastMessage: string,
    /** time of the last message sent (time is generated by firebase) */
    lastMessageTime: Timestamp,
    /** number which tracks unread messages */
    amountNewMessages: number,
    /** time user was last seen */
    lastCheckedTime: Timestamp,
    /** boolian which shows if the user is currently online or not */
    currentlyOnline: boolean,
}