import { Timestamp } from "@firebase/firestore";


/**
 * interface of Answer to a forumthread
 *
 * @export
 * @interface Answer
 */
export interface Answer {
    /** id of the answer */
    uid: string,
    /** text of the answer */
    text: string,
    /** timestamp of the answer generated by Firebase */
    timestamp: Timestamp,
    /** id of the thread the answer belongs to */
    threadUID: string,
}



/**
 * interface of a thread in the forum
 *
 * @export
 * @interface Thread
 */
export interface Thread {
    /** id of the thread */
    uid: string,
    /** timestamp of creation generated by firebase */
    created: Timestamp,
    /** title or header of the thread */
    title: string,
    /** text and therefore content of the thread */
    text: string,
    /** array of tags of type string e.g. ["web-dev", "testing", "girls-only"] */
    tags: string[],
    /** number representing the amount of answers of the thread
     * - used to show users the relevance and popularity of a thread */
    numberOfAnswers: number,
    /** timestamp of the last answer to the thread generated by firebase */
    lastAnswerTime: Timestamp,
    /** number representing the views of a thread */
    views: number,
    /** array with searchable keyphrases */
    keywords: string[],
}
