import { Timestamp } from "@firebase/firestore";



/**
 * Interface for a Usernotification object e.g. Mentorship request
 *
 * @export
 * @interface Notification
 */
export interface Notification{
    /** name of reqeusting user */
    fromName: string,
    /** image of user who sent request */
    fromPhotoURL: string,
    /** id of user who sent request */
    fromUID: string,
    /** id of user who should receive */
    toUID: string,
    /** optional a text of the notification. Might be the appilcation of the mentee */
    text?: string,
    /** number defining the type of the notification and therefore decides which interaction elements to show
     *  Type: 1 = Mentor-Anfrage (Buttons: Annehmen, Ablehnen); 2 = Info (Keine Buttons) */
    type: number,
    /** Timestamp of creation generated by Firebase */
    when: Timestamp,
    /** id of notification */
    uid: string
}